### ISSUE TITLE
使い方について

### ISSUE THREAD

**Issue by Mindful** [nymwa/arteraro#1]
Saluton! Mia nomo estas Josh. (ぐらいのエスペラント語しか覚えていなくて、すいません)

言語処理学会第27回年次大会に参加した方に論文を紹介され、とても面白く読ませていただきました。
私も文法誤り訂正関係の研究をしており、ちょうど人工データの生成方法を探していたところなので、研究でerarigiloを使えたらと思っています（もちろん引用します）。

リポジトリをクローンして、自分のパソコンで走らせることはできましたが、良ければ聞きたいことがいくつかあります。

1. きれいなデータから誤りデータを生成する手順としては、以下のような流れで合っているでしょうか？ 特に、この3つ以外に必要なコマンドがないのを確かめたいと思っています。`en_erg_script`もあると思いますが、下記の3つとすることが同じという理解で合っているでしょうか？

```
en_erg_preprocess < test.text > test.json
en_erg_noise < test.json > errored.json
en_erg_form < errored.json > output.tsv
```
 2. コンフィグファイル(config.yaml)は[arterarejo](https://github.com/nymwa/arterarejo/tree/main/noised)にたくさんあるようですが、全部同じでしょうか？違いがあるとしたら、最も性能が出たものや論文で使ったものなどおすすめがあれば助かります。
 3. arteraroをツールとして使いやすくするためのプルリクエストは受け付けていますか？以前からこういうツールがあれば良いのにと思っているので、少しでも力になれたらと思います。最低限使いこなせたら英語での詳しいドキュメンテーションなど書けます。

**Comment by nymwa** [comment]
Saluton! （ちなみにですが，arteraroは英語以外の言語でも規則が作れたら良いなあと思って，敢えて英語ではなく，エスペラントで命名しています．エスペラントであることに気づいてくださってありがとうございます．）

論文の方，ご一読ありがとうございます．

1. 誤り生成の方法ですが，`en_erg_script`で生成されるスクリプトは，基本的にはJoshさんの書かれた3つのコマンドと等価です．そのため，その3つのコマンドを使うという手順で問題ありません．
`en_erg_script`は，ABCIやTSUBAMEなどでgrid engineを用いて実行するための補助として使うためのコマンドで，GNU parallelを使った並列化やBPEのコード，`qsub`を使ったジョブスケジューリングのためのコードも生成します．

2. `arterarejo/noised`以下のファイルについてですが，1億2千万文での事前学習に用いた `all_*` 以下，事前学習に用いる単言語コーパスの規模を変えた `4m,8m,16m,32m`に関しては，config.yamlは同じです．誤り生成を各ディレクトリ以下で行うために別々のconfigファイルを置いていますが，`en_erg_noise -c /path/to/config.yaml`とすることもできます．`8m_only_*, 8m_wo_*`では，誤り生成規則のablationを行うために，config.yamlの中身は`all_*`などとは異なるものとなっています．

3. 機能の提案のissueやプルリクエストなどは大歓迎です．すべてのリクエストを反映できるかどうかはわかりませんが，良いプルリクエストはなるべく受け付けるように努めます．

**Comment by Mindful** [comment]
丁寧な返信ありがとうございます！
実はエスペラント語を一時期勉強していましたが、残念ながら日本語の勉強との両立ができませんでした。いつかはまた勉強できたらと思いますが。。。
言語ごとにかかる手間が多そうですが、英語以外の言語でも規則作れたら確かに良さそうですね。

1)と2)に関してはわかりました。私の研究室にABCIやTSUBAMEのようなものがあるかどうかは調べないとわかりませんが、あれば`en_erg_script`も試してみます。どの道並列化しないと処理できるデータ量じゃなさそうです。

3)も了解しました。arteraroを研究に組み込んで使ってみるまでうまく貢献できないと思いますが、使っている間に気づくことや改善できそうなところがあれば積極的に提案したりプルリクエストしたりします。

**Comment by nymwa** [comment]
en_erg_noiseはGNU parallelで並列化する前提で書いていて，ABCIのXeon Gold 6148 (20コア 40スレッド) 1プロセッサで40プロセスにして並列化すると，1時間あたり1000万文程度に誤り生成ができます．1プロセスだとこの20~30倍程度の時間がかかると思うので，1時間あたり~50万文程度しか処理できず，計算リソースが十分でないと結構大変だと思います．

使い方については解決したということで，closeします．
